title: Messages
modelClass: Thodin\SoobshcheniyaOtFormyZahvata\Models\Messages
list: $/thodin/soobshcheniyaotformyzahvata/models/messages/columns.yaml
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '50'
showSetup: true
showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
